Importing sprites and movement realization
Kiuh/Tank-Survivors pull request #4
Opened 2023-10-27 16:39 UTC by ShovelD

2023-10-27 17:03 UTC, Kiuh requested changes

2023-10-27 17:03 UTC, Kiuh commented on Tank Survivors/Assets/JoystickPackage/Scripts/Editor/DynamicJoystickEditor.cs
For the editor scripts also add namespaces and formatting

2023-10-27 17:03 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Tank/Moving.cs
> +        public Vector2 MovementDirection { get; set; }
and if you want to interact with it from other script, make property for created field

2023-10-28 12:01 UTC, ShovelD commented on Tank Survivors/Assets/Scripts/Tank/Moving.cs
> +            tankRigidBody = tank.GetComponent<Rigidbody2D>();
fixed

2023-10-28 12:01 UTC, ShovelD commented on Tank Survivors/Assets/JoystickPackage/Scripts/Joysticks/DynamicJoystick.cs
all scripts for joyticks now have namespace and they was formated with formatter

2023-10-28 13:24 UTC, Kiuh approved these changes
Apply formatting to joystick package and you can merge

2023-10-28 13:51 UTC, merged