Rework main level logic
Kiuh/Tank-Survivors pull request #41
Opened 2024-02-22 16:12 UTC by ShovelD

2024-02-22 16:54 UTC, LeshaTola requested changes
I think you can now leave this implementation with ability and take next task that will rewre all enemy structure to modular system, and bosses will be the same as enemies but with unique modules. System will bw the same as system in weapons modules.

2024-02-22 16:54 UTC, LeshaTola commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Abilities/IAbility.cs
> +        public bool IsActive { get; }
Add default implementation logic to Enable|disable ability directly in interface

2024-02-22 16:54 UTC, LeshaTola commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Boss.cs
> +        public string EnemyName => throw new System.NotImplementedException();
Why it's not implemented?

2024-02-22 16:54 UTC, LeshaTola commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Boss.cs
> +            }
Check formatting settings, var should not be used

2024-02-22 16:54 UTC, LeshaTola commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Boss.cs
> +        }
What The Focuses in this code, where correct implementation?

2024-02-22 16:54 UTC, LeshaTola commented on Tank Survivors/Assets/Scripts/Enemies/EnemyProducers/BossProducer.cs
> +        [AssetList(CustomFilterMethod = "EnemiesFilter")]
use nameof() in attributes

2024-02-22 16:54 UTC, LeshaTola commented on Tank Survivors/Assets/Scripts/General/EnemyGenerator.cs
> +        private void TryGenerateBoss()
Try means return true or false, and why you trying to generate it? Just create it

2024-02-22 16:54 UTC, LeshaTola commented on Tank Survivors/Assets/Scripts/General/EnemyGenerator.cs
> +        }
Don't do this, just stopping producing enemies will be enough.

2024-02-24 14:06 UTC, Kiuh approved these changes

2024-02-24 14:06 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Abilities/MovementAbility.cs
> +    public class MovementAbility : IAbility
```suggestion
    public class Movement : IAbility
```

2024-02-24 14:06 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Abilities/IAbility.cs
> +        }
```suggestion
        public void Execute();
        public void Enable()
        {
            IsActive = true;
        }
        public void Disable()
        {
            IsActive = false;
        }
```

2024-02-24 14:06 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Abilities/MovementAbility.cs
> +        public Vector3 CalculateDirection()
```suggestion
        private Vector3 CalculateDirection()
```

2024-02-24 14:06 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Abilities/MovementAbility.cs
> +        public void RotatateToTank(Vector3 direction)
```suggestion
        private void RotatateToTank(Vector3 direction)
```

2024-02-24 14:06 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/BossStats.cs
> +    public class BossStats
```suggestion
    public class Stats
```

2024-02-25 20:12 UTC, LeshaTola commented on Tank Survivors/Assets/Scripts/Enemies/Bosses/Stats.cs
> +}
maybe you should do it like enemies. Using SO and structs

2024-02-25 20:14 UTC, LeshaTola approved these changes

2024-02-25 20:15 UTC, merged