Enemy progression system
Kiuh/Tank-Survivors pull request #43
Opened 2024-03-02 16:24 UTC by ShovelD

2024-03-03 13:30 UTC, Kiuh requested changes
<img width="371" alt="image" src="https://github.com/Kiuh/Tank-Survivors/assets/30412223/88f6591e-7b5b-4201-ae9c-e24f267f599b">

- Move producer name inside foldout group and if possible, assign it when you choose producer type.
- Move modules inside a prefab and don't show it in this place
- Make start and end radius as external link to SO and create small, normal and bug radius, and incapsulate get creating point into that configs

<img width="349" alt="image" src="https://github.com/Kiuh/Tank-Survivors/assets/30412223/2af34d63-4f51-41ad-a75e-ed1c85597a8f">

- Move this progressor into other config, that can modify any of modules that he mentioned.
- In progressor config, make sure i can customize progression for every module separely.
- Make interval more intuitive (maybe in seconds and show readonly field in minutes)

2024-03-03 13:30 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Drone.cs
>          public string EnemyName { get; private set; }
Do we really need `EnemyName` ?

2024-03-03 13:30 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/EnemyProducers/ConstantEnemyProducer.cs
> +                var enemy = UnityEngine
Chek formatting, var shouldn't be used

2024-03-03 13:30 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Modules.cs
> +    public interface IModule : ICloneable { }
Why you use `ICloneable`

2024-03-03 13:30 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Modules.cs
> +        }
using `object` very bad, find other way to do what you need

2024-03-03 13:30 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/General/EnemyProgressor.cs
> +        }
Why you update enemies in update? Just update them when you creating them.

2024-03-03 13:58 UTC, ShovelD commented on Tank Survivors/Assets/Scripts/Enemies/Drone.cs
>          public string EnemyName { get; private set; }
i've never added this property to interface. it appeared after one of your's commit

2024-03-04 16:07 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/Drone.cs
>          public string EnemyName { get; private set; }
So, remove it

2024-03-07 22:08 UTC, Kiuh requested changes

2024-03-07 22:08 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/General/EnemyProgressor.cs
> +        }
Little wrong way.
Better make producers ask for current time, they will calculate stats for enemy that they want to create depended on time and progression config that they have.
As I see, you will delete `LastUpdateTime`

2024-03-12 16:57 UTC, Kiuh approved these changes
And check that game is correctly builds with no errors and works in build

2024-03-12 16:57 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/ModuleUpgrades.cs
> +            return module;
```suggestion
            return producer.Modules.GetConcrete<T, IModule>();
```

2024-03-12 16:57 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/General/EnemyGenerator.cs
>          private List<BossProducer> bossProducers;
```suggestion
        private List<BossProducer> bossProducers = new();
```

2024-03-12 16:57 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Enemies/EnemyProducers/DefaultEnemyProducer.cs
>          }
Move this method into Circle zone

2024-03-12 17:26 UTC, merged