Basic enemy implementation
Kiuh/Tank-Survivors pull request #6
Opened 2023-11-03 14:10 UTC by ShovelD

2023-11-03 20:06 UTC, Kiuh requested changes

2023-11-11 12:39 UTC, ShovelD commented on Tank Survivors/Assets/Scripts/Configs/Enemies/MovingEnemy.cs
don't understand what do you mean

2023-11-11 12:41 UTC, ShovelD commented on Tank Survivors/Assets/Scripts/Enemies/MovingEnemy.cs
> +    {
i simply removed MovingEnemy, now all enemies implement IEnemy without any other classes or interfaces

2023-11-13 15:36 UTC, Kiuh approved these changes

2023-11-13 15:36 UTC, Kiuh commented on Tank Survivors/Assets/Scripts/Configs/Enemies/MovingEnemy.cs
Make it class with `[Serializable]` attribute, not scriptable object

2023-11-13 16:39 UTC, merged